cc_library(
    name = "test_library_mocks",
    srcs = glob(["*.hpp"]),
    deps = [
        "@googletest//:gtest_main",
        "//Libraries/TestLibrary/src/lib:test_lib",
    ],
    visibility = [
        "//visibility:public"
    ]
)
