cc_library(
    name = "TestLibrary",
    hdrs = ["TestLibrary.h"],
    copts = [
        "-I Libraries/TestLibrary/src"
    ],
    deps = [ "//Libraries/TestLibrary/src/lib:test_lib"],
    visibility = ["//visibility:public"]
)
