cc_library(
    name = "TestLibrary",
    hdrs = ["TestLibrary.h"],
    copts = [
        "-I Libraries/TestLibrary/src",
    ],
    visibility = ["//visibility:public"],
    deps = ["//Libraries/TestLibrary/src/lib:test_lib"],
)
