load("@rules_cc//cc:cc_test.bzl", "cc_test")

cc_test(
    name = "test_utils",
    srcs = ["test.cc"],
    deps = [
        "//Libraries/Utils/src:Utils",
        "@googletest//:gtest_main",
    ],
)
