cc_library(
    name = "axis_to_actuator_engine_lib",
    hdrs = glob(["*.h"]),
    copts = ["-I Libraries/AxisToActuatorEngine/src"],
    visibility = [
        "//Libraries/AxisToActuatorEngine/src:__pkg__",
        "//Libraries/AxisToActuatorEngine/test:__pkg__",
    ],
)
