cc_library(
    name = "tmc_api",
    hdrs = ["TMC_API.h"],
    copts = [
        "-I Libraries/TMC_API"
    ],
    deps = [
        # "//Libraries/TMC_API/helpers:tmc_api_helpers",
        # "//Libraries/TMC_API/ic:tmc_api_ic",
        "//Libraries/TMC_API/lib:tmc_api_lib",
    ],
    visibility = [
        "//visibility:public"
    ]
)

# cc_library(
#     name = "AD22100Sensor",
#     hdrs = ["AD22100Sensor.h"],
#     copts = [
#         "-I libraries/Device/src",
#         "-I libraries/AD22100Sensor/src"
#     ],
#     deps = [
#         "//libraries/AD22100Sensor/src/lib:ad22100sensor"
#     ],
#     visibility = [
#         "//visibility:public"
#     ]
# )