// #include "helpers/API_Header.h"
// #include "helpers/Bits.h"
// #include "helpers/CRC.h"
// #include "helpers/Config.h"
// #include "helpers/Constants.h"
// #include "helpers/Functions.h"
// #include "helpers/Macros.h"
// #include "helpers/RegisterAccess.h"
// #include "helpers/Types.h"

// #include "ic/TMC2300.h"
// #include "ic/TMC2300_Constants.h"
// #include "ic/TMC2300_Fields.h"
// #include "ic/TMC2300_Register.h"

#include "lib/API_Header.h"
#include "lib/Bits.h"
#include "lib/CRC.h"
#include "lib/Config.h"
#include "lib/Constants.h"
#include "lib/Functions.h"
#include "lib/Macros.h"
#include "lib/RegisterAccess.h"
#include "lib/Types.h"

#include "lib/TMC2300.h"
#include "lib/TMC2300_Constants.h"
#include "lib/TMC2300_Fields.h"
#include "lib/TMC2300_Register.h"
