cc_library(
    name = "pico_test",
    hdrs = [
        "pico/stdlib.h",
        "hardware/adc.h",
        "hardware/gpio.h",
        "types.h",
        "pico_test.h"
    ],
    # hdrs = glob(["hardware/*.h"], ["pico/*.h"]),
    # hdrs = ["pico_test.h"],
    visibility = ["//visibility:public"]
)
