cc_library(
    name = "AxisToActuatorEngine",
    hdrs = ["AxisToActuatorEngine.h"],
    copts = [
        "-I Libraries/AxisToActuatorEngine/src",
    ],
    visibility = ["//visibility:public"],
    deps = ["//Libraries/AxisToActuatorEngine/src/lib:axis_to_actuator_engine_lib"],
)
